version: 0.2

phases:
  pre_build:
    commands:
      - npm install -g create-react-app
      - npm install
  build:
    commands:
      - npm run build

artifacts:
  files:
    - '**/*'
  base-directory: devops-01-P2-TeamA/build