version: 0.2

phases:
  install:
    runtime-versions:
      - nodejs:16
    commands:
      - echo node version check
      - node -v
      - npm -v

  pre_build:
    commands:
      - npm install -g create-react-app
      - npm install
  build:
    commands:
      - npm run build

artifacts:
  files:
    - '**/*'
  base-directory: build